import Client from './Client';
import hentaiCommand from './commands/hentai';
import hugCommand from './commands/hug';
import playCommand from './commands/play';
import kissCommand from './commands/kiss';
import slapCommand from './commands/slap';
import cumCommand from './commands/cum';
import fuckCommand from './commands/fuck';
import analCommand from './commands/anal';
import bakaCommand from './commands/baka';
import patCommand from './commands/pat';
import nekoCommand from './commands/neko';

const client = new Client();
client.addCommand(['hentai'], hentaiCommand);
client.addCommand(['h', 'hug'], hugCommand);
client.addCommand(['play'], playCommand);
client.addCommand(['kiss'], kissCommand);
client.addCommand(['slap'], slapCommand);
client.addCommand(['cum'], cumCommand);
client.addCommand(['fuck'], fuckCommand);
client.addCommand(['anal'], analCommand);
client.addCommand(['baka'], bakaCommand);
client.addCommand(['pat'], patCommand);
client.addCommand(['neko'], nekoCommand);
client.connect();
